server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/workspace
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"                # exposes all actuator endpoints
  endpoint:
    health:
      show-details: always          # show full health info on /actuator/health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8081                      # exposes management endpoints on same port
  prometheus:
    enabled: true                   # enable prometheus metrics exposure
